// 子表业务流转动作(审批/办理按钮), 合并进对应 SUB_MODULES 配置; patch 字段 key 与各表配置一致, 由脚本生成勿手改
import type { IRowAction } from './modules';

export const SUB_ACTIONS: Record<string, IRowAction[]> = {
  adOpen: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过开户申请',
      confirmDescription: '确认审批通过该开户申请？',
      successMessage: '开户申请已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回开户申请',
      confirmDescription: '确认驳回该开户申请？',
      successMessage: '开户申请已驳回',
    },
    {
      key: 'open',
      label: '确认开通',
      hiddenWhenEquals: { field: 'status', value: '已开通' },
      patch: { status: '已开通' },
      confirmTitle: '确认开通账户',
      confirmDescription: '确认该账户已开通？',
      successMessage: '账户已标记开通',
    },
  ],
  adTransfer: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过转户申请',
      confirmDescription: '确认审批通过该转户申请？',
      successMessage: '转户申请已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回转户申请',
      confirmDescription: '确认驳回该转户申请？',
      successMessage: '转户申请已驳回',
    },
    {
      key: 'finish',
      label: '确认完成',
      hiddenWhenEquals: { field: 'status', value: '已完成' },
      patch: { status: '已完成' },
      confirmTitle: '完成转户',
      confirmDescription: '确认该转户已执行完成？',
      successMessage: '转户已完成',
    },
  ],
  refund: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '待退款' },
      patch: { status: '待退款' },
      confirmTitle: '通过退款申请',
      confirmDescription: '确认通过该退款申请，进入待退款？',
      successMessage: '退款申请已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回退款申请',
      confirmDescription: '确认驳回该退款申请？',
      successMessage: '退款申请已驳回',
    },
    {
      key: 'refunded',
      label: '确认退款',
      hiddenWhenEquals: { field: 'status', value: '已退款' },
      patch: { status: '已退款' },
      confirmTitle: '确认已退款',
      confirmDescription: '确认该笔退款已打款？',
      successMessage: '退款已完成',
    },
  ],
  reimburse: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过报销申请',
      confirmDescription: '确认审批通过该报销？',
      successMessage: '报销已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回报销申请',
      confirmDescription: '确认驳回该报销？',
      successMessage: '报销已驳回',
    },
    {
      key: 'pay',
      label: '确认付款',
      hiddenWhenEquals: { field: 'status', value: '已付款' },
      patch: { status: '已付款' },
      confirmTitle: '报销付款',
      confirmDescription: '确认该报销已付款？',
      successMessage: '报销已付款',
    },
  ],
  advance: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过垫款申请',
      confirmDescription: '确认通过该垫款申请？',
      successMessage: '垫款申请已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回垫款申请',
      confirmDescription: '确认驳回该垫款申请？',
      successMessage: '垫款申请已驳回',
    },
    {
      key: 'paid',
      label: '确认垫付',
      hiddenWhenEquals: { field: 'status', value: '已垫付' },
      patch: { status: '已垫付' },
      confirmTitle: '确认已垫付',
      confirmDescription: '确认该笔垫款已付出？',
      successMessage: '已标记垫付',
    },
    {
      key: 'repay',
      label: '确认还款',
      visibleWhenEquals: { field: 'status', value: '已垫付' },
      patch: { status: '已还款' },
      confirmTitle: '确认还款',
      confirmDescription: '确认该笔垫款已归还？还款后状态将变为「已还款」',
      successMessage: '垫款已还款',
    },
  ],
  stockUse: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过领用申请',
      confirmDescription: '确认通过该领用申请？',
      successMessage: '领用已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回领用申请',
      confirmDescription: '确认驳回该领用申请？',
      successMessage: '领用已驳回',
    },
  ],
  invoice: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'f9', value: '待开票' },
      patch: { f9: '待开票' },
      confirmTitle: '通过开票申请',
      confirmDescription: '确认通过该开票申请？',
      successMessage: '开票申请已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'f9', value: '已驳回' },
      patch: { f9: '已驳回' },
      confirmTitle: '驳开票申请',
      confirmDescription: '确认驳回该开票申请？',
      successMessage: '开票申请已驳回',
    },
    {
      key: 'issue',
      label: '开具发票',
      hiddenWhenEquals: { field: 'f9', value: '已开票' },
      patch: { f9: '已开票' },
      confirmTitle: '确认开具发票',
      confirmDescription: '确认该发票已开具？',
      successMessage: '发票已开具',
    },
    {
      key: 'send',
      label: '寄出发票',
      hiddenWhenEquals: { field: 'f9', value: '已寄出' },
      patch: { f9: '已寄出' },
      confirmTitle: '确认寄出',
      confirmDescription: '确认该发票已寄出？',
      successMessage: '发票已寄出',
    },
  ],
  salary: [
    {
      key: 'calc',
      label: '核算完成',
      hiddenWhenEquals: { field: 'status', value: '待发放' },
      patch: { status: '待发放' },
      confirmTitle: '完成工资核算',
      confirmDescription: '确认该笔工资已核算完成，进入待发放？',
      successMessage: '工资已核算，待发放',
    },
    {
      key: 'pay',
      label: '确认发放',
      hiddenWhenEquals: { field: 'status', value: '已发放' },
      patch: { status: '已发放' },
      confirmTitle: '发放工资',
      confirmDescription: '确认该笔工资已发放？',
      successMessage: '工资已发放',
    },
  ],
  expense: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过支出申请',
      confirmDescription: '确认审批通过该笔支出？',
      successMessage: '支出已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回支出申请',
      confirmDescription: '确认驳回该笔支出？',
      successMessage: '支出已驳回',
    },
    {
      key: 'pay',
      label: '确认付款',
      hiddenWhenEquals: { field: 'status', value: '已付款' },
      patch: { status: '已付款' },
      confirmTitle: '支出付款',
      confirmDescription: '确认该笔支出已付款？',
      successMessage: '支出已付款',
    },
  ],
  interviewInvite: [
    {
      key: 'send',
      label: '发送邀约',
      hiddenWhenEquals: { field: 'status', value: '已发送' },
      patch: { status: '已发送' },
      confirmTitle: '发送面试邀约',
      confirmDescription: '确认发送该面试邀约？',
      successMessage: '邀约已发送',
    },
    {
      key: 'confirm',
      label: '候选人确认',
      hiddenWhenEquals: { field: 'status', value: '已确认' },
      patch: { status: '已确认' },
      confirmTitle: '标记候选人已确认',
      confirmDescription: '确认候选人已接受邀约？',
      successMessage: '候选人已确认',
    },
    {
      key: 'finish',
      label: '完成面试',
      hiddenWhenEquals: { field: 'status', value: '已完成' },
      patch: { status: '已完成' },
      confirmTitle: '完成邀约流程',
      confirmDescription: '确认该面试已完成？',
      successMessage: '邀约流程已完成',
    },
  ],
  adCommission: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过提成申请',
      confirmDescription: '确认通过该广告提成？',
      successMessage: '广告提成已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回提成申请',
      confirmDescription: '确认驳回该广告提成？',
      successMessage: '广告提成已驳回',
    },
    {
      key: 'pay',
      label: '确认发放',
      hiddenWhenEquals: { field: 'status', value: '已发放' },
      patch: { status: '已发放' },
      confirmTitle: '发放提成',
      confirmDescription: '确认该提成已发放？',
      successMessage: '广告提成已发放',
    },
  ],
  videoCommission: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过提成申请',
      confirmDescription: '确认通过该视频提成？',
      successMessage: '视频提成已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回提成申请',
      confirmDescription: '确认驳回该视频提成？',
      successMessage: '视频提成已驳回',
    },
    {
      key: 'pay',
      label: '确认发放',
      hiddenWhenEquals: { field: 'status', value: '已发放' },
      patch: { status: '已发放' },
      confirmTitle: '发放提成',
      confirmDescription: '确认该提成已发放？',
      successMessage: '视频提成已发放',
    },
  ],
  deduct: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过扣减申请',
      confirmDescription: '确认通过该扣减？',
      successMessage: '扣减已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回扣减申请',
      confirmDescription: '确认驳回该扣减？',
      successMessage: '扣减已驳回',
    },
    {
      key: 'exec',
      label: '确认执行',
      hiddenWhenEquals: { field: 'status', value: '已执行' },
      patch: { status: '已执行' },
      confirmTitle: '执行扣减',
      confirmDescription: '确认该扣减已执行？',
      successMessage: '扣减已执行',
    },
  ],
  coinReturn: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'f3', value: '已通过' },
      patch: { f3: '已通过' },
      confirmTitle: '通过退币申请',
      confirmDescription: '确认通过该退币申请？',
      successMessage: '退币申请已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'f3', value: '已驳回' },
      patch: { f3: '已驳回' },
      confirmTitle: '驳回退币申请',
      confirmDescription: '确认驳回该退币申请？',
      successMessage: '退币申请已驳回',
    },
    {
      key: 'finish',
      label: '平台处理完成',
      hiddenWhenEquals: { field: 'f3', value: '已完成' },
      patch: { f3: '已完成' },
      confirmTitle: '完成退币',
      confirmDescription: '确认平台已处理完成？',
      successMessage: '退币已完成',
    },
  ],
  incentive: [
    {
      key: 'approve',
      label: '审批通过',
      hiddenWhenEquals: { field: 'status', value: '已通过' },
      patch: { status: '已通过' },
      confirmTitle: '通过激励申请',
      confirmDescription: '确认通过该激励？',
      successMessage: '激励已通过',
    },
    {
      key: 'reject',
      label: '审批驳回',
      hiddenWhenEquals: { field: 'status', value: '已驳回' },
      patch: { status: '已驳回' },
      confirmTitle: '驳回激励申请',
      confirmDescription: '确认驳回该激励？',
      successMessage: '激励已驳回',
    },
    {
      key: 'pay',
      label: '确认发放',
      hiddenWhenEquals: { field: 'status', value: '已发放' },
      patch: { status: '已发放' },
      confirmTitle: '发放激励',
      confirmDescription: '确认该激励已发放？',
      successMessage: '激励已发放',
    },
  ],
  rebate: [
    {
      key: 'arrive',
      label: '确认到账',
      hiddenWhenEquals: { field: 'f0', value: '已到账' },
      patch: { f0: '已到账' },
      confirmTitle: '确认后返到账',
      confirmDescription: '确认该笔后返已全额到账？',
      successMessage: '后返已到账',
    },
    {
      key: 'partial',
      label: '部分到账',
      hiddenWhenEquals: { field: 'f0', value: '部分到账' },
      patch: { f0: '部分到账' },
      confirmTitle: '标记部分到账',
      confirmDescription: '确认该笔后返仅部分到账？',
      successMessage: '已标记部分到账',
    },
  ],
  // 公海客资: 领取/分配/恢复
  pool: [
    { key: 'claim', label: '领取', hiddenWhenEquals: { field: 'f9', value: '已领取' }, patch: { f9: '已领取' }, confirmTitle: '领取客资', confirmDescription: '确认将此客资领取到自己名下？', successMessage: '客资已领取' },
    { key: 'assign', label: '分配', hiddenWhenEquals: { field: 'f9', value: '已分配' }, patch: { f9: '已分配' }, confirmTitle: '分配客资', confirmDescription: '确认将此客资分配给指定人员？', successMessage: '客资已分配' },
    { key: 'recover', label: '恢复', visibleWhenEquals: { field: 'f9', value: '无效' }, patch: { f9: '待分配' }, confirmTitle: '恢复客资', confirmDescription: '确认将此客资恢复为待分配？', successMessage: '客资已恢复' },
  ],
  // 线索: 转化
  clue: [
    { key: 'convert', label: '转化客户', hiddenWhenEquals: { field: 'f3', value: '已转化' }, patch: { f3: '已转化' }, confirmTitle: '转化线索', confirmDescription: '确认将此线索转化为正式客户？', successMessage: '线索已转化为客户' },
  ],
  // 样品: 邮寄/接收/归还
  sample: [
    { key: 'mail', label: '邮寄', hiddenWhenEquals: { field: 'f18', value: '已邮寄' }, patch: { f18: '已邮寄' }, confirmTitle: '邮寄样品', confirmDescription: '确认该样品已寄出？', successMessage: '样品已邮寄' },
    { key: 'receive', label: '接收', hiddenWhenEquals: { field: 'f18', value: '已接收' }, patch: { f18: '已接收' }, confirmTitle: '接收样品', confirmDescription: '确认已收到该样品？', successMessage: '样品已接收' },
    { key: 'return', label: '归还', hiddenWhenEquals: { field: 'f18', value: '已归还' }, patch: { f18: '已归还' }, confirmTitle: '归还样品', confirmDescription: '确认该样品已归还？', successMessage: '样品已归还' },
  ],
  // 外包: 费用结算
  outsource: [
    { key: 'settle', label: '费用结算', hiddenWhenEquals: { field: 'status', value: '已结算' }, patch: { status: '已结算' }, confirmTitle: '外包费用结算', confirmDescription: '确认该外包费用已结算？', successMessage: '外包费用已结算' },
  ],
  // 保证金押金: 收取/退还
  deposit: [
    { key: 'collect', label: '收取', hiddenWhenEquals: { field: 'status', value: '已收取' }, patch: { status: '已收取' }, confirmTitle: '收取保证金', confirmDescription: '确认该保证金已收取？', successMessage: '保证金已收取' },
    { key: 'return', label: '退还', hiddenWhenEquals: { field: 'status', value: '已退还' }, patch: { status: '已退还' }, confirmTitle: '退还保证金', confirmDescription: '确认该保证金已退还？', successMessage: '保证金已退还' },
  ],
  // 盘点: 盘盈盘亏
  stockCheck: [
    { key: 'profit', label: '盘盈', hiddenWhenEquals: { field: 'status', value: '已处理' }, patch: { status: '已处理' }, confirmTitle: '确认盘盈', confirmDescription: '确认该盘盈差异已处理？', successMessage: '盘盈已处理' },
    { key: 'loss', label: '盘亏', hiddenWhenEquals: { field: 'status', value: '已处理' }, patch: { status: '已处理' }, confirmTitle: '确认盘亏', confirmDescription: '确认该盘亏差异已处理？', successMessage: '盘亏已处理' },
  ],
  // 资产: 登记/盘点/折旧
  asset: [
    { key: 'register', label: '登记', hiddenWhenEquals: { field: 'status', value: '已登记' }, patch: { status: '已登记' }, confirmTitle: '登记资产', confirmDescription: '确认该资产已登记？', successMessage: '资产已登记' },
    { key: 'check', label: '盘点', hiddenWhenEquals: { field: 'status', value: '已盘点' }, patch: { status: '已盘点' }, confirmTitle: '资产盘点', confirmDescription: '确认完成该资产盘点？', successMessage: '资产盘点已完成' },
  ],
  // 归还: 登记/逾期标红
  stockReturn: [
    { key: 'register', label: '登记归还', hiddenWhenEquals: { field: 'status', value: '已归还' }, patch: { status: '已归还' }, confirmTitle: '登记归还', confirmDescription: '确认该物品已归还？', successMessage: '已登记归还' },
  ],
  // 采购订单: 入库
  purchaseOrder: [
    { key: 'stockIn', label: '确认入库', hiddenWhenEquals: { field: 'status', value: '已入库' }, patch: { status: '已入库' }, confirmTitle: '确认入库', confirmDescription: '确认该采购订单已完成入库？', successMessage: '已确认入库' },
  ],
  // 充值: 新建充值/到账
  recharge: [
    { key: 'arrive', label: '确认到账', hiddenWhenEquals: { field: 'status', value: '已到账' }, patch: { status: '已到账' }, confirmTitle: '确认充值到账', confirmDescription: '确认该笔充值已到账？', successMessage: '充值已到账' },
  ],
  // 收款: 确认/核销
  income: [
    { key: 'confirm', label: '确认', hiddenWhenEquals: { field: 'f10', value: '已确认' }, patch: { f10: '已确认' }, confirmTitle: '确认收款', confirmDescription: '确认该笔收款？', successMessage: '收款已确认' },
    { key: 'verify', label: '核销', hiddenWhenEquals: { field: 'f10', value: '已核销' }, patch: { f10: '已核销' }, confirmTitle: '核销收款', confirmDescription: '确认核销该笔收款？', successMessage: '收款已核销' },
  ],
  // 广告账户: 充值
  adAccount: [
    { key: 'recharge', label: '充值', hiddenWhenEquals: { field: 'status', value: '已充值' }, patch: { status: '已充值' }, confirmTitle: '广告账户充值', confirmDescription: '确认对该账户进行充值？', successMessage: '账户充值已提交' },
  ],
  // 报备: 审核
  report: [
    { key: 'review', label: '审核通过', hiddenWhenEquals: { field: 'status', value: '已审核' }, patch: { status: '已审核' }, confirmTitle: '审核报备', confirmDescription: '确认审核通过该报备？', successMessage: '报备已审核通过' },
  ],
  // 拍摄/场地费用: 登记
  shootCost: [
    { key: 'register', label: '登记费用', hiddenWhenEquals: { field: 'status', value: '已登记' }, patch: { status: '已登记' }, confirmTitle: '登记费用', confirmDescription: '确认登记该笔费用？', successMessage: '费用已登记' },
  ],
  // 视频订单: 批量通过/驳回
  videoOrder: [
    { key: 'approve', label: '通过', hiddenWhenEquals: { field: 'status', value: '已通过' }, patch: { status: '已通过' }, confirmTitle: '通过订单', confirmDescription: '确认通过该视频订单？', successMessage: '视频订单已通过' },
    { key: 'reject', label: '驳回', hiddenWhenEquals: { field: 'status', value: '已驳回' }, patch: { status: '已驳回' }, confirmTitle: '驳回订单', confirmDescription: '确认驳回该视频订单？', successMessage: '视频订单已驳回' },
  ],
  // 员工: 入职/转正/调岗/离职
  employee: [
    { key: 'onboard', label: '入职', hiddenWhenEquals: { field: 'status', value: '在职' }, patch: { status: '在职' }, confirmTitle: '确认入职', confirmDescription: '确认该员工已正式入职？', successMessage: '员工已入职' },
    { key: 'regularize', label: '转正', visibleWhenEquals: { field: 'status', value: '试用期' }, patch: { status: '在职' }, confirmTitle: '确认转正', confirmDescription: '确认该员工转正？', successMessage: '员工已转正' },
    { key: 'transfer', label: '调岗', patch: { status: '调岗中' }, confirmTitle: '发起调岗', confirmDescription: '确认发起该员工调岗流程？', successMessage: '调岗流程已发起' },
    { key: 'resign', label: '离职', patch: { status: '已离职' }, confirmTitle: '确认离职', confirmDescription: '确认该员工离职？', successMessage: '员工已离职' },
  ],
  // 库存: 库存流水+安全库存预警
  stock: [
    { key: 'flow', label: '库存流水', patch: { status: '已记录' }, confirmTitle: '记录流水', confirmDescription: '确认记录该笔库存流水？', successMessage: '库存流水已记录' },
    { key: 'alert', label: '预警', patch: { status: '预警' }, confirmTitle: '安全库存预警', confirmDescription: '确认标记该库存预警？', successMessage: '库存预警已标记' },
  ],
  // 行业ROI: 导入/导出/修正
  industryRoi: [
    { key: 'import', label: '导入', patch: { status: '已导入' }, confirmTitle: '导入ROI数据', confirmDescription: '确认导入该批ROI数据？', successMessage: 'ROI数据已导入' },
    { key: 'export', label: '导出', patch: { status: '已导出' }, confirmTitle: '导出ROI', confirmDescription: '确认导出该ROI报表？', successMessage: 'ROI报表已导出' },
    { key: 'correct', label: '修正', patch: { status: '已修正' }, confirmTitle: '修正ROI', confirmDescription: '确认修正该ROI数据？', successMessage: 'ROI数据已修正' },
  ],
  // 素材库: 上传
  material: [
    { key: 'upload', label: '上传', patch: { status: '已上传' }, confirmTitle: '上传素材', confirmDescription: '确认上传该素材？', successMessage: '素材已上传' },
    { key: 'approve', label: '审核通过', hiddenWhenEquals: { field: 'status', value: '已审核' }, patch: { status: '已审核' }, confirmTitle: '审核素材', confirmDescription: '确认审核通过该素材？', successMessage: '素材已审核通过' },
    { key: 'archive', label: '归档', patch: { status: '已归档' }, confirmTitle: '归档素材', confirmDescription: '确认归档该素材？', successMessage: '素材已归档' },
  ],
};
